export enum Routes {
  Root = '/',
  Contact = '/contact',
  Roadmap = 'https://formbuilder.canny.io',
  Docs = '/docs',
  Pricing = '/pricing',
  Blog = '/blog',
  Story = '/story',
  Careers = '/careers',
  TermsOfUse = '/terms-of-use',
  PrivacyPolicy = '/privacy-policy',
  CookiePolicy = '/cookie-policy',

  Auth = '/auth',
  Login = '/auth/login',
  Logout = '/auth/logout',
  SignUp = '/auth/signup',
  AuthError = '/auth/error',
  Totp = '/auth/totp',
  RecoveryCode = '/auth/recovery-code',
  ChangeEmail = '/auth/change-email',
  ChangeEmailRequest = '/auth/change-email/request',
  ChangeEmailInvalid = '/auth/change-email/invalid',
  ChangeEmailExpired = '/auth/change-email/expired',
  ForgotPassword = '/auth/forgot-password',
  ForgotPasswordSuccess = '/auth/forgot-password/success',
  ResetPassword = '/auth/reset-password',
  ResetPasswordRequest = '/auth/reset-password/request',
  ResetPasswordExpired = '/auth/reset-password/expired',
  ResetPasswordSuccess = '/auth/reset-password/success',
  VerifyEmail = '/auth/verify-email',
  VerifyEmailRequest = '/auth/verify-email/request',
  VerifyEmailExpired = '/auth/verify-email/expired',
  VerifyEmailSuccess = '/auth/verify-email/success',

  Dashboard = '/app',
  Home = '/app/home',
  Settings = '/app/settings',
  Account = '/app/settings/account',
  Profile = '/app/settings/account/profile',
  Security = '/app/settings/account/security',
  Notifications = '/app/settings/account/notifications',
  Organization = '/app/settings/organization',
  OrganizationInformation = '/app/settings/organization/information',
  Members = '/app/settings/organization/members',
  Billing = '/app/settings/organization/billing',
  Developers = '/app/settings/organization/developers',

  Invitations = '/invitations',
  InvitationRequest = '/invitations/request',
  InvitationAlreadyAccepted = '/invitations/already-accepted',
  InvitationRevoked = '/invitations/revoked',
  InvitationLogOutToAccept = '/invitations/log-out-to-accept',

  Onboarding = '/onboarding'
}
